# Generated by Django 6.0.5 on 2026-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstudio', '0002_subscriber_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
