# Generated by Django 6.0.1 on 2026-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='blog_images'),
        ),
    ]
