# Generated by Django 6.0.1 on 2026-02-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
